# Generated by Django 4.1 on 2023-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
